#!/bin/bash
#SBATCH --account=fudenber_735
#SBATCH --partition=gpu 
#SBATCH --gres=gpu
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=16GB
#SBATCH --time=3:59:00
#SBATCH --array=0-45

export TMPDIR=/scratch1/rahmanin/
export MYTMP=`mktemp -d -t`

readarray tasks < /home1/rahmanin/start/polychrom/projects/Dynamic_boundary_elements/simulations/2023-09-17_runfile.txt
task=${tasks[$SLURM_ARRAY_TASK_ID]}
echo $task


eval "$(conda shell.bash hook)"
conda activate openwpoly

python /home1/rahmanin/start/polychrom/projects/Dynamic_boundary_elements/simulations/simulation.py ${MYTMP}/${task}











